### ISSUE TITLE
multiline OSA script lines

### ISSUE THREAD

**Issue by HelpfulScripts** [brandonhorst/node-osa#4]
First of all: Thanks for providing this very helpful library! 

Proposal for an enhancement: 
For debugging the OSA function it would be helpful to run it in multiple lines. If an error is thrown, the message currently reference 'line 1' as the location. To accomplish this, I used the multiple -e option of osascript by replacing

    var escapedCall = functionCallString.replace(/^\s+/g, ' ').replace(/\n/g, '').replace(/'/g, "'\\''");
    var executeString = "osascript -l JavaScript -e '" + escapedCall + "'";

with 

    var escapedCall = functionCallString.replace(/^\s+/g, ' ').replace(/'/g, "'\\''").split('\n');
    var executeString = "osascript -l JavaScript";
    for (var i=1, r=0; r<escapedCall.length; r++) {
        console.log('*** ' + (i++) + ': ' + escapedCall[r]);
        executeString += " -e '" + escapedCall[r] + "'";
    }

If this is too verbose, remove the 'console.log' line. Errors will now be reported in the respective line of the function with an offset of 1 for the prefix code itself - hence `i` starts counting at `1` in the for loop above.

Cheers,
-HS

**Comment by brandonhorst** [comment]
That seems reasonable to me. Could you submit a PR?

**Comment by dylan-chong** [comment]
This appears to be what I am working on now. Was any progress made here?

**Comment by brandonhorst** [comment]
I'm open to PR's. It would be a quick fix, and I could get around to it eventually but not immediately

**Comment by dylan-chong** [comment]
Same here. Although I'm actually new to node as well. Did OP push any of his changes?

**Comment by brandonhorst** [comment]
Don't think he made any.

**Comment by dylan-chong** [comment]
Ok, I’ll give it a go some time

**Comment by dylan-chong** [comment]
It looks like you already have a pull request for it.

https://github.com/brandonhorst/node-osa/pull/5

**Comment by brandonhorst** [comment]
Oh jeez, right you are. Sorry for that absurd discussion! Merged, tested, and published.
