### ISSUE TITLE
How to access enum

### ISSUE THREAD

**Issue by loretoparisi** [brandonhorst/node-osa#7]
For the `Spotify` desktop app I have this `enum`

```objective-c
@class SpotifyApplication, SpotifyTrack, SpotifyApplication;

enum SpotifyEPlS {
	SpotifyEPlSStopped = 'kPSS',
	SpotifyEPlSPlaying = 'kPSP',
	SpotifyEPlSPaused = 'kPSp'
};
typedef enum SpotifyEPlS SpotifyEPlS;
```

I don't know how to access `SpotifyEPlS` enum given the application

```javascript
var spotify = Application('Spotify');
```

**Comment by brandonhorst** [comment]
Is this a question about `node-osa` in particular, or just Javascript OSA in general. `node-osa` just runs Javascript as it would run in the `Script Editor` - it doesn't make any fancy modifications. If you're having trouble writing code that runs in the Script editor, or translating your Applescript to Javascript, I'm afraid I can't help you.

**Comment by loretoparisi** [comment]
@brandonhorst uhm not sure actually, maybe both. I noticed that some references in javascript are as `function` like `currentTrack.name()`, while `name` is a property...

**Comment by brandonhorst** [comment]
So `node-osa` doesn't do any magic. If you look at the source, all it does is pass the source code of your function to the `osascript` system utility. This runs the script exactly as the `Script Editor` would, if `JavaScript` was selected as the language.

If you find some code that runs in `Script Editor`, but not in `node-osa`, then we've found a bug. But unfortunately, I can't help you write your scripts themselves. Sorry!

**Comment by loretoparisi** [comment]
@brandonhorst thanks for the clarification, but I still have a clue.
The issue to me is `osa` related of course, maybe you can point me in the right direction. Supposed to have a OSA interface in the `Script Editor` like let's say `current track`, this will result in my `npm-osa` in something like

```javascript
function myOSAFun() {
  var myApp = Application('myApp')
   console.log( myApp.currentTrack )
}
```

in

```javascript
osa(myOSAFun, function (error, state, log) {
     console.log( log );
     if (error) {
       console.log(error)
     }else{
       console.log( JSON.stringify(state,null,2) );
     }
   })
```

Thus resulting in this logging

```shell
function () {
    [native code]
}
```

so I assume that `myApp.currentTrack` was a function, but if I try to execute it like `myApp.currentTrack()` I will get an error like `undefined` function.

So question, is how can I get the right accessors, given that I can do these in script editor /  `osascript` command line?

Thank you.

**Comment by brandonhorst** [comment]
Would it be possible to post a reproducible example using built-in or freely available apps?

**Comment by loretoparisi** [comment]
@brandonhorst Yes, so this is a node module I was looking to [osa-spotify ](https://github.com/wtfaremyinitials/osa-spotify)

that makes use of osa, like

```javascript
play: function(cb) {
        return osaq(function() {
            Application('Spotify').play();
            return {};
        }, cb);
    },
```

This was using denodified version of osa

```javascript
var osa  = require('osa');
var osaq = q.denodeify(osa);
```

Inspired by that one I did then a basic snippet

```javascript
var osa = require('osa');
  var OSAGetCurrentState = function() {

   var spotify = Application('Spotify');

   var playerState = spotify.playerState;
   var currentTrack = spotify.currentTrack;

   console.log(  currentTrack, playerState);

   var status = {};
   status.track={};
   status.player={};
   status.playlists = {};

   status.player['player_state'] = playerState;

   if( currentTrack ) {
     status.track['track_name'] = currentTrack.name;

   }

  return status;

  }

   osa(OSAGetCurrentState, function (error, state, log) {
     console.log( log );
     if (error) {
       console.log(error)
     }else{
       console.log( JSON.stringify(state,null,2) );
     }
   })
```

**Comment by loretoparisi** [comment]
Ok it seems that this is not related to `node-osa` but to the application itself so some issue in the bridging like:

```javascript
var app=Application("Spotify");
app.currentTrack.properties()
```

will return a `Error 0: No error.`

while with `iTunes` that works. Strange thing, the dictionary it seems to be well defined and the bridging script header as well. More strange is that it works from command line for some properties like:

```shell
$ osascript -e 'tell application "Spotify" to name of current track'
This Is What You Came For
$ osascript -e 'tell application "Spotify" to properties of current track'
30:40: execution error: Spotify got an error: AppleEvent handler failed. (-10000)

while on `iTunes`...

$ osascript -e 'tell application "iTunes" to properties of current track'
class:URL track, id:79559, index:1, name:Won't Get Fooled Again, persistent ID:A39ACD9398278C41, database ID:79555, date added:date mercoledì 1 giugno 2016 16:51:27, time:8:36, duration:516.0, artist:The Who, album artist:, composer:Pete Townshend, album:Who's Next (Deluxe Edition), genre:Rock, track count:9, track number:0, disc count:0, disc number:1, volume adjustment:0, year:1971, comment:, EQ:, kind:, media kind:music, video kind:none, enabled:true, start:0.0, finish:516.0, played count:0, skipped count:0, compilation:false, rating:0, bpm:0, grouping:, bookmarkable:false, bookmark:0.0, shufflable:true, lyrics:, category:, description:, show:, season number:0, episode ID:, episode number:0, unplayed:false, sort name:, sort album:, sort artist:, sort composer:, sort album artist:, sort show:, release date:date venerdì 1 gennaio 1971 13:00:00, loved:false, album loved:false
macbookproloreto:scrobbler admin$ 
```

It seems to me a missing mapping somewhere!

**Comment by brandonhorst** [comment]
Yeah, the JS OSA implementation is a bit wonky. Hopefully Apple will improve it in the future!
