### ISSUE TITLE
Add a way to run a script from a file

### ISSUE THREAD

**Issue by dylan-chong** [brandonhorst/node-osa#8]
Is there a way to run a script that is loaded from a text file? I guess it
could be done with eval (`eval('function osaFunction(arg) {' + fileContents +
'}');`, but I am unsure as to whether this would be a good idea or not.

**Comment by brandonhorst** [comment]
If you'd like to do that, you may just want to `child_process::exec` the `osascript` utility directly. There isn't much reason to use this if you don't want integration with your code file.

**Comment by dylan-chong** [comment]
Good idea. I'll give that a go
